LICENSE
package.json

Update package.json to use WTFPL rather than BSD

---

public/index.html

index.html incorrect docs for /field, now fixed

Fixing docs for /field

---

.gitignore
README.md
lib/filters/i18n.coffee
lib/foaas.coffee
lib/server.coffee
package.json
public/index.html

Ping @maetl, @xenph, @philipmuir

Long Awaited i18n Basic Support

---

lib/operations/tucker.coffee
public/index.html
spec/operations/tucker_spec.coffee

https://www.youtube.com/watch?v=LXoopmFkDBU#t=70s

Add Malcolm Tucker mode.

---

lib/operations/bucket.coffee
public/index.html
spec/operations/bucket_spec.coffee

Per the classic jwz fuck-off: http://www.jwz.org/blog/2003/05/no-good-deed-goes-unpunished/

Add bucket operation

---

lib/operations/shutup.coffee
public/index.html
spec/operations/shutup_spec.coffee

Adds operation "shutup/:name/:from". Generates output like:
:name, shut the fuck up.
- :from

Add /shutup operation.

---

README.md

Created a telegram messenger bot for Foass [@fuck_off_bot](https://telegram.me/fuck_off_bot)

Telegram bot for Foaas

---

lib/operations/off_with.coffee
spec/operations/off_with.spec.coffee

As a fan of Trailer Park Boys, I thought an operation offering the simple ability to tell someone to fuck off with something would be a nice addition to FOAAS.
Take it or leave it.  Love your work!
-Jackson

Off-With Operation Proposal

---

public/index.html

small update to the /thumbs/ doco to reflect current behaviour.
@tomdionysus

Updated thumbs doco

---

public/index.html

load bootstrap css file over appropriate protocol

---

package.json

Latest Deps

---

lib/operations/greed.coffee
public/index.html
spec/operations/greed_spec.coffee

Signed-off-by: Matt Ranostay <mranostay@gmail.com>

Add Gordon Gekko /greed/ option

---

lib/renderers/html.coffee
spec/renderers/html_spec.coffee

Slack example:
Twitter Card example:
Should mostly address #111

metatags for twitter cards, slack unfurls etc.

---

lib/operations/mornin.coffee
public/index.html
spec/operations/mornin_spec.coffee

Provide a hearty good mornin.

---

README.md

Hey, I've written a client for Golang

---

lib/filters/i18n.coffee

translate subtitle when using i18n filter

---

lib/operations/pulp.coffee
public/index.html
spec/operations/pulp_spec.coffee

I'm not sure if there are legal reasons not to add a movie quote, but this is one of my favorites, and given that I love FOAAS, I had to create this one.  I completely understand if legally this can't be merged, but had fun making it either way.

Added /pulp/:language/:from and updates to the index file

---

lib/operations/anyway.coffee
public/index.html
spec/operations/anyway.coffee

Creates #112: 'Who the fuck are you anyway?'

Add 'who the fuck are you anyway'

---

lib/operations/horse.coffee
spec/operations/horse_spec.coffee

Adding  #133 'Fuck you and the horse you rode in on.'

add 'Fuck you and the horse you rode in on' from  #133

---

public/index.html

https://dev.twitter.com/cards/getting-started#opengraph

Add Twitter/Open Graph tags

---

public/index.html

fix for issue #155

---

lib/operations/deraadt.coffee
public/index.html
spec/operations/deraadt_spec.coffee

Also added index.html info for #133 as well as for #136.

Added /deraadt/:name/:from #136

---

lib/operations/blackadder.coffee
public/index.html
spec/operations/blackadder_spec.coffee

Adding a Blackadder quote in (with additional FO) because someone had a cunning plan and requested one. Issue #123

Blackadder!

---

lib/operations/problem.coffee
public/index.html
spec/operations/problem_spec.coffee

I added a new API call that returns:
What the fuck is you problem :name?
- :from

Created a new call: What the fuck is your problem?

---

lib/operations/too.coffee
public/index.html
spec/operations/too.coffee

fuck-you-too operation added

---

lib/operations/cocksplat.coffee
public/index.html
spec/operations/cocksplat_spec.coffee

Returns content of the form:
'Fuck off :name, you worthless cocksplat. - :from'

Adds fuck off, worthless cocksplat functionality

---

lib/operations/particular.coffee
public/index.html
spec/operations/particular_spec.coffee

This adds the ability to tell someone "Fuck this :thing in particular."

Add "Fuck this :thing in particular."

---

lib/operations/problem.coffee
public/index.html
spec/operations/problem_spec.coffee

department of a 'not a native speaker here' but either that grammar is wrong as I suspect, or the joke is lost on me.  which happens ...

correct 'you problem' to 'your problem'

---

lib/operations/ridiculous.coffee
public/index.html
spec/operations/ridiculous.coffee

This endpoint was requested in #116.
Added, tests passing. Over to you @tomdionysus

Added new 'ridiculous' endpoint

---

lib/operations/rtfm.coffee
public/index.html
spec/operations/rtfm_spec.coffee

RTFM is a classic!
Telling people to fuck off by referring to the manual is timeless.

Add RTFM operation

---

README.md

Thank you so much for your great work. In particular the foaas Slack integration resulted in a significant speed up in our team communication. We would like to give back and have developed an Alexa Skill, in case you guys are interested.

Alexa Integration

---

lib/operations/king.coffee
spec/operations/king_spec.coffee

In the king operation there should be a comma between 'Christ' and :name.

Add comma to king.coffee

---

lib/operations/thinking.coffee
spec/operations/thinking_spec.coffee

Specifically, I changed
from: what the fuck _where_ you actually thinking?
to:     what the fuck _were_ you actually thinking?

Fixed grammar for /thinking

---

lib/operations/fyyff.coffee
spec/operations/fyyff_spec.coffee

Added “Fuck you, you fucking fuck.”

---

lib/renderers/html.coffee
spec/renderers/html_spec.coffee

Why:
I would like to send foaas links via iMessage and have the preview be
something appropriate.
This PR:
Adds an og:title to the html render in the meta tag which will be picked
up by iMessage for preview purposes.
Before:
After:

Rich iMessage previews

---

.gitattributes
Dockerfile
README.md
package-lock.json

1. Added a Dockerfile to support quick startup development environment. A little security hardening would be beneficial before deploying to the wild.
2. Added a `.gitattributes` file to ensure line ending compatiblity across systems, converting all to use linux-style line endings e.g. `lf`.

added simple docker image to run locally

---

lib/operations/logs.js
spec/operations/logs.js

Solves https://github.com/tomdionysus/foaas/issues/217

Add a logs operation

---

lib/operations/zero.js
spec/operations/zero_spec.js

Fixed issue /zero/:from returns incorrect english #209

---

lib/operations/fewer.js
spec/operations/fewer_spec.js

Sorry, I just couldn't help myself.. Specs pass ok here.

Add "GFY name, you'll disappoint fewer people"

---

lib/operations/even.js
lib/operations/legend.js
lib/operations/rockstar.js
spec/operations/even_spec.js
spec/operations/legend_spec.jc
spec/operations/rockstar_spec.js

Implemented three new operations. "even", "rockstar" and "legend"
Testing done - new specs as well as existing, bring up local server and touch each endpoint

Implement the operations: even, legend and rockstar

---

lib/operations/idea.js
spec/operations/idea_spec.js

Reference: https://getyarn.io/yarn-clip/72b3f125-1466-4b28-9248-661cd145fb27

Add "That sounds like a fucking great idea!" operation

---

HTTPSE.txt

I didn't update the April 1st 2016 date because I'm starting to thing we've been stuck in a time loop ever since that day started. I'm starting to thing we've been stuck in a time loop ever since that day started.
https://www.youtube.com/watch?v=iPGnK-09ako

All the things

---

lib/filters/shoutcloud.js

I NOTICED A TYPO IN YOUR SO HERE IS A QUICK PR TO FIX IT. :)

FIX TYPO IN SHOUTCLOUD FILTER

---

lib/operations/dumbledore.js
spec/operations/dumbledore_spec.js

Added feature dumbledore - 
- Added new file in /lib/operations
- Added new specification file in /spec/operations

added feature dumbledore

---

lib/operations/yeah.js
spec/operations/yeah_spec.js

/yeah/:from
should output Fuck YEAH! -:from

Add a yeah endpoint

---

lib/operations/understand.js
spec/operations/understand_spec.js

Added new understand feature

---

lib/operations/absolutely.js
spec/operations/absolutely.js

**Added absolutely**
returns: `Absolutely fucking Not, TEST, No Fucking Way!`
URL:
> /anyway/:company/:from
files I created:
>lib\operations\absolutely.js
>spec\operations\absolutely.js
`this is my first time doing a PR to a public repo. don't come at me if I missed some procedures on the way!`

absolutely
