tomdionysus/foaas

lib/foaas.coffee
Previously FOAAS would return the index page as a default, now returns a 404 error for non-existent routes.
=> Non-existent routes now return 404

README.md
The top-level documentation on the website still talked about 0.1.2
=> mark README.md as 0.1.3 too

public/index.html
Fixed typo in resource /because and added leading slash to the /madison
resource.
=> Fixed typo and missing slash.

README.md
This PR adds my in development API of FOAAS for Java to the list of available APIs.
=> Update README.md, Add Java API

public/index.html
I love the examples that succinctly exemplify how to tell some to F* off. This PR makes those example links in the description clickable so people can readily experience the joy of the service with a single click.
=> Making the example links clickable in the description

lib/operations/keepcalm.coffee, public/index.html, spec/operations/keepcalm.coffee
Can either be used in the "classic" way: `/keepcalm/code on/Matthias`
"Keep the fuck calm and `code on`! – `Matthias`" …
… or with a little more fantasy: `/keepcalm/chill the fuck out/Matthias`
"Keep the fuck calm and `chill the fuck out`! – `Matthias`"
=> Added keepcalm resource (Keep the fuck calm and :reaction! - :from)

lib/operations/dosomething.coffee, public/index.html, spec/operations/dosomething.coffee
Can either be used in the "classic" way: `/dosomething/Commit/code/Matthias`
"`Commit` the fucking `code`! – `Matthias`" … 
… or "extended": `/dosomething/Arnold, get to/choppa/Matthias`
"`Arnold, get to` the fucking `choppa`! – `Matthias`"
=> Added dosomething resource (:do the fucking :something! - :from)

HTTPSE.txt
Hey @tomdionysus,
A few small changes for `DRAFT03213` for the Hyper Text Transport Protocol Sarcasm Extension (HTTPSE/1.0)
- Added expected caller behaviour when receiving a `613`
- Re-ordered `606` and `610` and fixed numbering
Also because your editor sucks a fat one, I have introduced a few trailing whitespace removals. To view this PR without whitespace append `?w=1` to the URL.
Have a fucking nice day,
-Charles
=> Document expected caller behaviour when receiving a 613

package.json
More recent versions prevents npm starting:
ubuntu@surge:~/FOAAS/GITPUSH/foaas$ npm start
> foaas@0.1.8 start /home/ubuntu/FOAAS/GITPUSH/foaas
> ./node_modules/.bin/coffee lib/server.coffee
TypeError: app.use() requires middleware functions
at EventEmitter.use (/home/ubuntu/FOAAS/GITPUSH/foaas/node_modules/express/lib/application.js:209:11)
at EventEmitter.wrappedAppUse [as use] (/home/ubuntu/FOAAS/GITPUSH/foaas/node_modules/newrelic/lib/instrumentation/express.js:348:11)
at Object.module.exports.register (/home/ubuntu/FOAAS/GITPUSH/foaas/lib/filters/i18n.coffee:17:9)
at FOAAS.module.exports.FOAAS.loadFilters (/home/ubuntu/FOAAS/GITPUSH/foaas/lib/foaas.coffee:90:14)
at FOAAS.loadFilters (/home/ubuntu/FOAAS/GITPUSH/foaas/lib/foaas.coffee:1:1)
at new FOAAS …
=> Pinned i18next

public/index.html
These each only accept one parameter and not two as the documenation
showed.
=> Correct endpoints for looking, no, give and zero

lib/operations/ing.coffee, public/index.html, spec/operations/ing_spec.coffee
Its important to be able to place more emphasis in a simple and adverbial way when telling someone to fuck off. In some parts of the world telling someone to 'Fucking fuck off' provides more than reasonable urgency in needing to fuck off promptly.
=> Ability to tell someone to 'Fucking fuck off' by use of a 'Fucking' adverb

README.md
=> The old link was 404d

lib/operations/greed.coffee, spec/operations/greed_spec.coffee
Renames the `fields` keys in `Greed` operation to match the rest of the foaas operations. 
Currently, the `Greed` is the only operation which doesn't return its `fields` with `name` and `field` as  keys (besides `Version`).
=> Renames fields keys

README.md
- Added link to [react-foaas-card](https://github.com/circa10a/react-foaas-card)
This library is an npm installable react component that supports calling foaas and populating the content in a material ui card for web applications.
[Doc site/Demo](https://github.com/circa10a/react-foaas-card)
=> Add link to react-foaas-card for React framework support

README.md
Hi!
I've created a provider plugin for Terraform to provide the available REST routes as data sources.
https://github.com/m13t/terraform-provider-foac
=> Added link to Terraform provider

lib/filters/i18n.js
This commit arranges the issue #199 which was causing translation
issues.
Remote service call has been migrated to GET method, and separator has
been changed for a single non-common char.
The main issue behind the bug was the URL query-string scaping. Now the
query-string is built using the provided method by the request
library
=> [ISSUE-199] i18n.js: bugfix. Support special chars

lib/renderers/html.js, spec/renderers/html_spec.js
The [example](https://foaas.com/asshole/farts) contains
```
<title>FOAAS - Fuck you, asshole. - - farts</title>
```
Those two hyphens are just too much.
=> Don't double hyphenate the html title

README.md
Added link to .Net Core Client Repository.
Difference between already existing .NET client and this one:
- existing client uses .NET Framework.
- this one uses .NET Core 3.1 framework (and .NET standard 2.1 too) and supports all methods defined in foaas api at the moment.
=> added .net core client repository to README.md

README.md
=> Add alternative python api client

README.md
This includes my web client in the README. I've added a new section for GUI clients.  
Hosted at: https://hamza1311.github.io/fuck-off/ 
Let me know if there's anything that needs to be changed.
=> Add my web client in readme
